name: unsure_angular_dart
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_forms: ^2.1.2
  dorker: ^0.1.4
  unsure:
    path: ../

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.6.0
  build_test: ^0.10.8
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  test: ^1.6.0
