name: unsure
description: >
  An easy to use probabilistic notation, and a package that can parse it
  and calculate with it.
version: 0.1.1
homepage: https://github.com/filiph/unsure

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  args: ^1.5.2
  petitparser: '>=2.4.0 <4.0.0'
  t_stats: ^2.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
